### ISSUE TITLE
[Error] ionic cordova build android --prod 

### ISSUE THREAD

**Issue by rogerin** [tiaguinho/ionic2-mask-directive#3]
$ ionic cordova build android --prod 

[11:57:05]  build prod started ...
[11:57:05]  clean started ...
[11:57:05]  clean finished in 5 ms
[11:57:05]  copy started ...
[11:57:05]  ngc started ...
[WARN] Error occurred during command execution from a CLI plugin (@ionic/cli-plugin-cordova). Your plugins may be out of
       date.
**Error: Unexpected value 'Ionic2MaskDirective in /Users/rogerio/Documents/ChegaJa/iboltt/ibolttapp/node_modules/ionic2-mask-directive/index.d.ts' declared by the module 'AppModule in /Users/rogerio/Documents/ChegaJa/iboltt/ibolttapp/src/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.**

$ ionic info

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 2.1.4
    @ionic/cli-plugin-cordova       : 1.4.1
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3 browser 4.1.0 ios 4.4.0
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.11.0
    OS         : macOS Sierra
    Xcode      : Xcode 8.3.3 Build version 8E3004b
    ios-deploy : 1.9.1
    ios-sim    : 5.0.13
    npm        : 5.0.3

**Comment by Aleziii** [comment]
Hi, i had the same problem during compilation --prod.

Just need to add the following line in the source code  "node_modules/ionic2-mask-directive/index.ts"

`import { Directive } from '@angular/core';`

`@Directive({
    selector: '[mask]' // Attribute selector
  })`


In this compilation the Ionic is a bit more demanding in syntax.

**Comment by tiaguinho** [comment]
Can you share how do you use the plugin?

**Comment by marcusdurao** [comment]
Bom dia Tiago !! Tive o mesmo problema.
Importei a diretiva no modulo.
Na página Html está assim
<ion-input type="text" mask="(99) 9999-9999" placeholder="(__) ____-____" formControlName="usua_ds_telefone" required></ion-input>

**Comment by marcusdurao** [comment]
Bom dia Tiago !!  Estou com o mesmo problema quando faço o build --prod. 
Importei a diretiva no modulo. 
Na página Html está assim
<ion-input type="text" mask="(99) 9999-9999" placeholder="(_) ____-___" formControlName="usua_ds_telefone" required></ion-input>

**Comment by ikezili** [comment]
To resolve this problem , just change in index.ts (Ionic2MaskDirective) the lines:

**Line: 36**
From
        const matches = v.match(/[a-zA-Z0-9]+/g);
To
        var matches = v.match(/[a-zA-Z0-9]+/g);

**Line 40**
From
          const chars = this.mask.split('');
TO
          var chars = this.mask.split('');

**Comment by tiaguinho** [comment]
Thank you @ikezili I already push new version with this fix.
