### ISSUE TITLE
 [Error] generate apk for production

### ISSUE THREAD

**Issue by alaordev** [tiaguinho/ionic2-mask-directive#5]
This framework work's fine in dev mode, but when i'm generate the apk, the following error is triggered:

https://user-images.githubusercontent.com/21992161/30773458-3fc147f0-a047-11e7-9dea-25b5c801fb0b.png

Apparently the Angular dont recognized anymore the sintaxe in line 12 to create a class, probably requiring the sintaxe "export class Ionic2MaskDirective { here the implementation }"

Is the ionic version 3.6.0

**Comment by steveacalabro** [comment]
+1

**Comment by joelsonrocha** [comment]
já tem mais de um mês e nenhuma resposta. Estou com o mesmo problema, esse plugin funcionou legal, e de forma fácil, porém tem esse problema, e não passa nos testes.

**Comment by ikezili** [comment]
To resolve this problem , just change in index.ts (Ionic2MaskDirective) the lines:

Line: 36
From
const matches = v.match(/[a-zA-Z0-9]+/g);
To
var matches = v.match(/[a-zA-Z0-9]+/g);

Line 40
From
const chars = this.mask.split('');
TO
var chars = this.mask.split('');
